#!/usr/bin/env python3
"""
Automated Mawaqit Prayer Times Uploader
Handles Gmail 2FA and uploads CSV prayer times to Mawaqit backoffice
"""

import imaplib
import email
import re
import time
import os
import csv
from datetime import datetime
from playwright.sync_api import sync_playwright, expect

def get_latest_mawaqit_2fa_code(gmail_user, gmail_app_password, max_wait=120):
    """
    Fetch the latest 2FA code from Gmail for Mawaqit
    """
    print("🔍 Checking Gmail for 2FA code...")
    
    start_time = time.time()
    while time.time() - start_time < max_wait:
        try:
            # Connect to Gmail via IMAP
            imap = imaplib.IMAP4_SSL("imap.gmail.com")
            imap.login(gmail_user, gmail_app_password)
            imap.select("inbox")

            # Search for recent emails from Mawaqit
            status, messages = imap.search(None, '(FROM "noreply@mawaqit.net" OR FROM "no-reply@mawaqit.net")')
            
            if status != 'OK' or not messages[0]:
                print("⏳ No Mawaqit emails found, waiting...")
                time.sleep(10)
                continue

            mail_ids = messages[0].split()
            
            # Check the most recent emails for 2FA code
            for mail_id in reversed(mail_ids[-5:]):  # Check last 5 emails
                status, msg_data = imap.fetch(mail_id, "(RFC822)")
                if status != 'OK':
                    continue
                    
                raw_msg = msg_data[0][1]
                msg = email.message_from_bytes(raw_msg)
                
                # Get email date
                email_date = email.utils.parsedate_to_datetime(msg['Date'])
                
                # Only process emails from the last 10 minutes
                if (datetime.now(email_date.tzinfo) - email_date).total_seconds() > 600:
                    continue
                
                # Extract email body
                body = ""
                if msg.is_multipart():
                    for part in msg.walk():
                        if part.get_content_type() == "text/plain":
                            try:
                                body += part.get_payload(decode=True).decode('utf-8', errors='ignore')
                            except:
                                continue
                else:
                    try:
                        body = msg.get_payload(decode=True).decode('utf-8', errors='ignore')
                    except:
                        continue

                # Look for 6-digit verification code
                code_match = re.search(r'\b(\d{6})\b', body)
                if code_match and 'verification' in body.lower():
                    code = code_match.group(1)
                    print(f"✅ Found 2FA code: {code}")
                    imap.close()
                    imap.logout()
                    return code
            
            print("⏳ No recent 2FA code found, waiting...")
            imap.close()
            imap.logout()
            time.sleep(10)
            
        except Exception as e:
            print(f"❌ Error checking email: {e}")
            time.sleep(10)
    
    print("❌ Timeout waiting for 2FA code")
    return None

def read_prayer_times_csv(athan_csv_path, iqama_csv_path):
    """
    Read prayer times from CSV files generated by scraper
    Returns dict with days as keys and prayer times as values
    """
    prayer_times = {}
    
    try:
        # Read Athan times
        athan_times = {}
        with open(athan_csv_path, 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                day = row.get('Day')
                if day:
                    athan_times[int(day)] = {
                        'fajr': row.get('Fajr', ''),
                        'sunrise': row.get('Sunrise', ''),
                        'dhuhr': row.get('Dhuhr', ''),
                        'asr': row.get('Asr', ''),
                        'maghrib': row.get('Maghrib', ''),
                        'isha': row.get('Isha', '')
                    }
        
        # Read Iqama times
        iqama_times = {}
        with open(iqama_csv_path, 'r', encoding='utf-8') as file:
            reader = csv.DictReader(file)
            for row in reader:
                day = row.get('Day')
                if day:
                    iqama_times[int(day)] = {
                        'fajr': row.get('Fajr', ''),
                        'dhuhr': row.get('Dhuhr', ''),
                        'asr': row.get('Asr', ''),
                        'maghrib': row.get('Maghrib', ''),
                        'isha': row.get('Isha', '')
                    }
        
        # Combine both into prayer_times dict
        for day in athan_times:
            prayer_times[day] = {
                'athan': athan_times[day],
                'iqama': iqama_times.get(day, {})
            }
    
    except Exception as e:
        print(f"❌ Error reading CSV files: {e}")
        return {}
    
    print(f"📊 Loaded {len(prayer_times)} days of prayer times from CSV files")
    return prayer_times

def upload_to_mawaqit(mawaqit_email, mawaqit_password, gmail_user, gmail_app_password, prayer_times_dir):
    """
    Main function to login to Mawaqit and upload prayer times
    """
    print("🚀 Starting Mawaqit upload process...")
    
    # Get current month name for CSV files
    current_month = datetime.now().strftime('%B')
    athan_csv_path = os.path.join(prayer_times_dir, f'athan_times_{current_month}.csv')
    iqama_csv_path = os.path.join(prayer_times_dir, f'iqama_times_{current_month}.csv')
    
    # Check if CSV files exist
    if not os.path.exists(athan_csv_path) or not os.path.exists(iqama_csv_path):
        print(f"❌ CSV files not found:")
        print(f"   Athan: {athan_csv_path}")
        print(f"   Iqama: {iqama_csv_path}")
        return False
    
    # Read prayer times from CSV files
    prayer_times = read_prayer_times_csv(athan_csv_path, iqama_csv_path)
    if not prayer_times:
        print("❌ No prayer times found in CSV files")
        return False
    
    with sync_playwright() as p:
        # Launch browser
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()
        
        try:
            # Navigate to Mawaqit login
            print("🌐 Navigating to Mawaqit login...")
            page.goto("https://mawaqit.net/en/backoffice/login", wait_until="networkidle")
            
            # Fill login form
            print("📝 Filling login credentials...")
            page.fill('input[type="email"]', mawaqit_email)
            page.fill('input[type="password"]', mawaqit_password)
            
            # Submit login
            page.click('button[type="submit"]')
            print("🔑 Login submitted, waiting for 2FA...")
            
            # Wait for 2FA page or dashboard
            page.wait_for_load_state("networkidle")
            
            # Check if 2FA is required
            if "verification" in page.content().lower() or "code" in page.content().lower():
                print("📧 2FA required, fetching code from Gmail...")
                
                # Get 2FA code from email
                verification_code = get_latest_mawaqit_2fa_code(gmail_user, gmail_app_password)
                
                if not verification_code:
                    print("❌ Failed to get 2FA code")
                    return False
                
                # Enter 2FA code
                code_input = page.locator('input[placeholder*="code" i], input[name*="code" i], input[type="text"]').first
                code_input.fill(verification_code)
                
                # Submit 2FA
                page.click('button[type="submit"]')
                print("✅ 2FA code submitted")
                
                page.wait_for_load_state("networkidle")
            
            # Navigate to mosque/prayer times configuration
            print("🏛️ Navigating to prayer times configuration...")
            
            # Look for mosque/configuration links (adjust selectors as needed)
            try:
                # Try different possible navigation paths
                if page.locator('a:has-text("Mosque")').count() > 0:
                    page.click('a:has-text("Mosque")')
                elif page.locator('a:has-text("Configuration")').count() > 0:
                    page.click('a:has-text("Configuration")')
                elif page.locator('a:has-text("Prayer Times")').count() > 0:
                    page.click('a:has-text("Prayer Times")')
                
                page.wait_for_load_state("networkidle")
                
                # Look for Athan/Iqama or Prayer Times section
                if page.locator('a:has-text("Athan")').count() > 0:
                    page.click('a:has-text("Athan")')
                elif page.locator('a:has-text("Prayer")').count() > 0:
                    page.click('a:has-text("Prayer")')
                
                page.wait_for_load_state("networkidle")
                
            except Exception as e:
                print(f"⚠️ Navigation error: {e}")
                print("🔍 Current page content preview:")
                print(page.content()[:500] + "...")
            
            # Here you would add the specific logic to fill prayer times
            # This part needs to be customized based on Mawaqit's actual form structure
            print("📅 Filling prayer times...")
            
            # Example of how prayer times would be filled (needs customization for Mawaqit's interface)
            for day, times in prayer_times.items():
                print(f"Processing day {day}...")
                # You'll need to inspect Mawaqit's form and adjust these selectors
                # Example structure:
                # - times['athan']['fajr'] = Fajr Athan time
                # - times['iqama']['fajr'] = Fajr Iqama time
                # etc.
            
            print("⚠️ Prayer time filling logic needs to be customized for Mawaqit's interface")
            
            print("✅ Upload process completed!")
            return True
            
        except Exception as e:
            print(f"❌ Error during upload: {e}")
            return False
        finally:
            browser.close()

def main():
    """
    Main entry point
    """
    # Get credentials from environment variables
    mawaqit_email = os.getenv('MAWAQIT_USER')
    mawaqit_password = os.getenv('MAWAQIT_PASS')
    gmail_user = os.getenv('GMAIL_USER')
    gmail_app_password = os.getenv('GMAIL_APP_PASSWORD')
    
    # Path to your prayer times directory
    prayer_times_dir = os.getenv('PRAYER_TIMES_DIR', './prayer_times')
    
    if not all([mawaqit_email, mawaqit_password, gmail_user, gmail_app_password]):
        print("❌ Missing required environment variables")
        print("Required: MAWAQIT_USER, MAWAQIT_PASS, GMAIL_USER, GMAIL_APP_PASSWORD")
        return False
    
    success = upload_to_mawaqit(
        mawaqit_email=mawaqit_email,
        mawaqit_password=mawaqit_password,
        gmail_user=gmail_user,
        gmail_app_password=gmail_app_password,
        prayer_times_dir=prayer_times_dir
    )
    
    if success:
        print("🎉 Mawaqit upload completed successfully!")
    else:
        print("💥 Mawaqit upload failed!")
    
    return success

if __name__ == "__main__":
    main()
